charadas = [("mantem sempre o mesmo tamanho, nao importa o peso?","balanca"),
("o que detestamos na praia e adoramos na panela?","caldo"),
("o que eh que anda com os pe na cabeca?","piolho"),
("o que eh, o que eh? que eh irma de minha tia e nao eh minha tia?","mae"),
("o que eh, o que eh? de dia tem quatro pes e de noite tem seis?","cama"),
("o que eh, o que eh? anda deitado e dorme em pe?","pe"),
("qual o sobrenome que todo mundo tem?", "costa"),
("quem morre em pe?","vela"),
("tem cabeca e nao eh gente, tem dente e nao eh pente?","alho"),
("o que eh que nasce grande e morre pequeno?","lapis"),
("eh nome de mulher e nome de homem. ia mas acabou nao indo?","isaias"),
("quem inventou a fila?","formiga"),
("na televisao cobre um pais; no futebol, atrai a bola; em casa incentiva o lazer. O que eh?","rede"),
("o que eh que se poe na mesa, parte, reparte mas nao se come?","baralho"),
("dois vizinhos. um nao vai a casa do outro e os dois nao se veem por causa de um morrinho? Quem sao eles?","olhos"),
("o que eh, o que eh? do tamanho de uma bolota e enche a casa ate a porta?","luz"),
("o que e que quanto mais rugas tem mais novo eh?","pneu"),
("o que eh, o que eh,se voce mudar uma letra em meu nome, ira aparecer o nome do animal que eh meu maior inimigo","rato"),
("qual a coisa mais veloz do mundo?","pensamento"),
("o que eh que corre em volta do pasto inteiro sem se mexer?","cerca"),
("qual a cidade sulamericana que pende nos galhos da arvore?","lima"),
("tem coroa, mas nao eh rei, tem raiz, mas nao eh planta?","dente"),
("o que eh, o que eh, nao tem pe e corre, tem leito e nao dorme, quando para,morre?", "rio"),
("o que eh o que eh, uma caixinha de bom parecer, nao ha carpinteiro que saiba fazer?","noz"),
("o que eh, o que eh? que nao se come, mas eh bom para se comer?","talher"),
("o que eh, o que eh? que mesmo atravessando o rio, consegue nao se molhar?", "ponte"),
("o que eh o que eh: nao tem olhos, mas pisca, nao tem boca, mas comanda?","semaforo"),
("o que eh o que eh: quanto mais eu tiro mais eu tenho?","fotografias"),
("o que eh que anda com a barriga para tras?","pernas"),
("o que eh, o que eh? me diga se for capaz. me diga quem eh aquele que num instante se quebra se alguem diz o nome dele?","silencio"),
("o que eh, o que eh, que entra na agua e nao se molha?", "sombra"),
("o que eh, o que eh, quanto mais se tira mais aumenta?","buraco"),
("o que eh, o que eh, uma casinha branca sem tranca e sem janela?", "ovo"),
("o que eh, o que eh, tem asa mas nao voa, tem bico mas nao bica?","bule"),
("o que eh, o que eh, quanto mais se seca, mais molhada fica?","toalha"),
("o que eh, o que eh, da um pulo e se veste de noiva?","pipoca"),
("o que eh, o que eh, que eh meu, mas meus amigos usam mais do que eu?","nome"),
("o que eh, o que eh, quanto mais a gente perde, com mais a gente fica?","sono")
]
