telaInicial() :- write(".------------------------------------------------------------------------."),nl,
				 write("|                                                                        |"),nl,
				 write("|                             Enigma de Cesar                            |"),nl,
				 write("|                                                                        |"),nl,
				 write("|                                                                        |"),nl,
				 write("|       A historia conta que, para se comunicar com seus generais, Julio |"),nl,
				 write("| Cesar utilizava um sistema simples de substituicao, no qual cada letra |"),nl,
				 write("| da mensagem original era trocada pela letra que se situa tres posicoes |"),nl,
				 write("| a sua frente. Esse metodo e popularmente conhecido como Cifra de Cesar.|"),nl,
				 write("|                                                                        |"),nl,
				 write("|           A B C D E F G H I J K L M N O P Q R S T U V W X Y Z          |"),nl,
				 write("|           - - - - - - - - - - - - - - - - - - - - - - - - - -          |"),nl,
				 write("|           D E F G H I J K L M N O P Q R S T U V W X Y Z A B C          |"),nl,
				 write("|                                                                        |"),nl,
				 write("|  Utilize a Cifra de Cesar para descobrir o que a Esfinge esta falando! |"),nl,
				 write("|                                                                        |"),nl,
				 write("'------------------------------------------------------------------------'"),nl.
				 
desenhaEsfinge() :- write("                               --------   "),nl,
					write("                            --------------"),nl,
					write("                          ---------|--------"),nl,
					write("                         --- | | | | | | | ---"),nl,
					write("                        -----| | | | | | |-----"),nl,
					write("                       -------           -------"),nl,
					write("                       -------   0   0   -------"),nl,
					write("                       -------     |     -------"),nl,
					write("                        ------     ~     ------"),nl,
					write("                         -----   _____   -----"),nl,
					write("                          ---     ___    ---"),nl,
					write("                          ---     ___    ---"),nl,
					write("                           --      _     --"),nl.
					
regras() :- write(".------------------------------------------------------------------------."),nl,
			write("|                                                                        |"),nl,
			write("|                                Regras                                  |"),nl,
			write("|                                                                        |"),nl,
			write("| 1. Para decifrar a mensagem da esfinge, decifre primeiro tres palavras.|"),nl,
			write("| 2. A cada palavra decifrada, um terco da mensagem original eh revelada.|"),nl,
			write("| 3. Apos revelada a mensagem, responda a pergunta que a esfinge fez.    |"),nl,
			write("| 4. Use as dicas a seu favor! Por exemplo, se a palavra a ser decifrada |"),nl,
			write("|    for 'xgw', e a chave for igual a 2, troque cada letra pela que esta |"),nl,
			write("|    2 posicoes atras.                                                   |"),nl,
			write("|    Como resultado, voce obtera 'veu' como resposta.                    |"),nl,
			write("| 5. Utilize apenas letras minusculas, sem acentuacao.                   |"),nl,
			write("|                                                                        |"),nl,
			write("------------------------------------------------------------------------'|"),nl.
